name: resolve-cloud deploy
description: deploying an applicaiton to reSolve cloud
inputs:
  app_directory:
    description: target application directory
    required: true
  app_name:
    description: override application name
    required: false
    default: ''
  generate_app_name:
    description: automatically generate uniquie app name
    required: false
    default: 'false'
  deploy_args:
    description: custom resolve-cloud deploy command arguments
    required: false
    default: ''
  resolve_api_url:
    description: reSolve cloud service API url
    required: true
  resolve_user:
    description: reSolve cloud service user
    required: true
  resolve_token:
    description: reSolve cloud service refresh token
    required: true
  resolve_version:
    description: reSolve framework version override
    required: false
  npm_registry:
    description: private NPM registry
    required: false

outputs:
  deployment_id:
    description: deployed application id
  app_name:
    description: deployed application name
  app_url:
    description: deployed application url
  app_runtime:
    description: deployed applicaiton runtime version

runs:
  using: 'node12'
  main: 'index.js'
  post: 'cleanup.js'
