name: CI/CD

on:
  push:
    branches: [ dev, feature/github-actions ]
  pull_request:
    branches: [ dev, feature/github-actions ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && (startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'fix/')))

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
        
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Prettier
        run: if [ "$(node_modules/.bin/prettier --list-different "**/*.js")" ]; then echo "Prettier failed" exit 1; fi

      - name: ESLint
        run: yarn lint

      - name: Unit-tests
        run: yarn test

      - name: Integration testing
        run: yarn test:integration
        
  e2e-macOS-test:
    needs: [smoke-test]
    
    runs-on: resolve-mac-mini
    
    if: github.event_name == 'pull_request' && (startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'fix/'))

    steps:
      - uses: actions/checkout@v2
        
      - name: Install
        run: yarn install --frozen-lockfile
      
      - name: E2E test
        run: yarn test:e2e
